CREATE TABLE "chaves_portal_unico" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chaves_portal_unico_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"clientId" varchar(255) NOT NULL,
	"clientSecretCifrado" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chaves_portal_unico_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
CREATE TABLE "usuario_empresas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usuario_empresas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"importadorId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "chaves_portal_unico" ADD CONSTRAINT "chaves_portal_unico_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usuario_empresas" ADD CONSTRAINT "usuario_empresas_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usuario_empresas" ADD CONSTRAINT "usuario_empresas_importadorId_importadores_id_fk" FOREIGN KEY ("importadorId") REFERENCES "public"."importadores"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "usuario_empresas_usuario_importador" ON "usuario_empresas" USING btree ("userId","importadorId");--> statement-breakpoint
CREATE INDEX "usuario_empresas_importador" ON "usuario_empresas" USING btree ("importadorId");--> statement-breakpoint

-- Mesma regra da 0001: RLS ligado e sem políticas bloqueia a Data API pública do Supabase.
-- O app conecta como dono das tabelas (role postgres) e não é afetado.
ALTER TABLE "usuario_empresas" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chaves_portal_unico" ENABLE ROW LEVEL SECURITY;
