CREATE TABLE "importador_chaves_portal" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "importador_chaves_portal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"importadorId" integer NOT NULL,
	"clientId" varchar(255) NOT NULL,
	"clientSecretCifrado" text NOT NULL,
	"atualizadoPor" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "importador_chaves_portal_importadorId_unique" UNIQUE("importadorId")
);
--> statement-breakpoint
ALTER TABLE "importador_chaves_portal" ADD CONSTRAINT "importador_chaves_portal_importadorId_importadores_id_fk" FOREIGN KEY ("importadorId") REFERENCES "public"."importadores"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "importador_chaves_portal" ADD CONSTRAINT "importador_chaves_portal_atualizadoPor_users_id_fk" FOREIGN KEY ("atualizadoPor") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint

-- Mesma regra da 0001: RLS ligado e sem políticas bloqueia a Data API pública do Supabase.
ALTER TABLE "importador_chaves_portal" ENABLE ROW LEVEL SECURITY;
